version: "3.9"

services:
  postgres:
    container_name: rentapark
    image: postgres:15
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "rentapark"
    ports:
      - "5434:5434"